/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Sidebar from "./Sidebar";
import Header from "./Header";
import StatCard from "./StatCard";
import SalesDetails from "./SalesDetails";
import DealsDetails from "./DealsDetails";
function Dashboard() {
  return (
    <div className="overflow-hidden bg-white">
      <div className="flex gap-5 max-md:flex-col">
        <Sidebar />
        <main className="flex flex-col ml-5 w-[83%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col px-px mx-auto w-full bg-slate-100 max-md:max-w-full">
            <Header />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/2a91f7101b5cac181afa2ad5e4f0703163fd1190a392c51390f4a77f2896d3a7?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
              alt="Dashboard overview"
              className="object-contain w-full max-md:max-w-full"
            />
            {/* <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/27ce8bbfa8b63313afd7f370aaf9666cf3ae5769592b31dd3120a618e86e6f8d?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
              alt=""
              className="object-contain z-10 mt-0 w-px aspect-[0]"
            /> */}
            <section className="flex z-10 flex-col mt-0 mr-8 ml-8 max-md:mt-0 max-md:mr-2.5 max-md:max-w-full">
              <h1 className="self-start text-3xl font-bold tracking-normal text-neutral-800">
                Dashboard
              </h1>
              <div className="mt-7 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col">
                  <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ff3e576ebeaac99f3ce65df9387bdd4e2998060eab5a38de9cdb31b04d89f9b?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
                      alt="Dashboard chart"
                      className="object-contain grow shrink-0 max-w-full rounded-none aspect-[1.63] w-[262px] max-md:mt-8"
                    />
                  </div>
                  <StatCard
                    title="Total Order"
                    value="10293"
                    trend="up"
                    percentage="1.3%"
                  />
                  <StatCard
                    title="Total Sales"
                    value="$89,000"
                    trend="down"
                    percentage="4.3%"
                  />
                  <StatCard
                    title="Total Pending"
                    value="2040"
                    trend="up"
                    percentage="1.8%"
                  />
                </div>
              </div>
              <SalesDetails />
              <DealsDetails />
            </section>
          </div>
        </main>
      </div>
    </div>
  );
}

export default Dashboard;
