/**
 * This code was generated by Builder.io.
 */
import React from "react";

function DealsDetails() {
  const deals = [
    {
      productName: "Apple Watch",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/46b0df6b72d2196f8375c4534a319b509389e8e04b0f6a728b7a0d1426c2b568?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7",
      location: "6096 Marjolaine Landing",
      dateTime: "12.09.2019 - 12.53 PM",
      piece: "423",
      amount: "$34,295",
      status: "Delivered",
    },
  ];

  return (
    <section className="flex flex-col px-8 pt-8 pb-4 mt-7 w-full bg-white rounded-2xl shadow-[6px_6px_54px_rgba(0,0,0,0.05)] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full leading-none max-md:max-w-full">
        <h2 className="my-auto text-2xl font-bold text-neutral-800">
          Deals Details
        </h2>
        <div className="flex gap-4 px-4 py-2.5 text-xs font-medium text-right whitespace-nowrap bg-white rounded border border-solid border-neutral-300 text-zinc-800 text-opacity-40">
          <span>October</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/111fd0868388956f825ac25ee037644d295049379b5acf6e86ea84aed5304cc0?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
            alt="Dropdown icon"
            className="object-contain shrink-0 w-2.5 aspect-square"
          />
        </div>
      </div>
      <div className="flex flex-wrap gap-5 justify-between py-4 pr-16 pl-6 mt-8 w-full text-sm font-bold rounded-xl bg-slate-100 text-neutral-800 max-md:px-5 max-md:max-w-full">
        <div className="flex gap-10 max-md:max-w-full">
          <div>Product Name</div>
          <div>Location</div>
          <div>Date - Time</div>
        </div>
        <div className="flex gap-10 whitespace-nowrap">
          <div>Piece</div>
          <div>Amount</div>
          <div>Status</div>
        </div>
      </div>
      {deals.map((deal, index) => (
        <div
          key={index}
          className="flex flex-wrap gap-10 self-center mt-6 w-full text-sm font-semibold max-w-[1013px] text-neutral-800 max-md:max-w-full"
        >
          <div className="flex gap-4">
            <img
              loading="lazy"
              src={deal.image}
              alt={deal.productName}
              className="object-contain shrink-0 w-9 rounded-none aspect-square"
            />
            <div className="my-auto bg-blend-normal">{deal.productName}</div>
          </div>
          <div className="flex flex-wrap flex-auto gap-10 items-center my-auto max-md:max-w-full">
            <div className="grow self-stretch my-auto bg-blend-normal">
              {deal.location}
            </div>
            <div className="self-stretch my-auto bg-blend-normal basis-auto">
              {deal.dateTime}
            </div>
            <div className="self-stretch my-auto bg-blend-normal">
              {deal.piece}
            </div>
            <div className="self-stretch my-auto bg-blend-normal">
              {deal.amount}
            </div>
            <div className="self-stretch px-4 py-1 font-bold text-white whitespace-nowrap bg-teal-500 rounded-2xl">
              {deal.status}
            </div>
          </div>
        </div>
      ))}
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d469fe62d3b22b35d37c5053e168345f60357fc25b8eb35b0eacdcc34d8ab2a0?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
        alt="Decorative line"
        className="object-contain mt-5 w-full bg-blend-normal aspect-[1000] max-md:max-w-full"
      />
    </section>
  );
}

export default DealsDetails;
