/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Header() {
  return (
    <header className="flex flex-wrap gap-5 justify-between py-3.5 pr-8 pl-20 w-full bg-white max-md:px-5 max-md:max-w-full">
      <form className="flex gap-3.5 px-4 py-2.5 my-auto text-sm text-center whitespace-nowrap rounded-2xl border border-solid bg-slate-100 border-neutral-300 text-neutral-800">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2184b94f9823c083598b31ecc5e470d8559ec223ed5778fcda9419e76fdf2b9b?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
          alt=""
          className="object-contain shrink-0 self-start bg-blend-normal aspect-square w-[15px]"
        />
        <input
          type="search"
          placeholder="Search"
          className="flex-auto bg-blend-normal bg-transparent border-none"
          aria-label="Search"
        />
      </form>
      <div className="flex gap-6 items-center">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/613304ec143b87fb5f22963a92bc9e8e71fbaae34f41916e50065540ba3c1e05?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
          alt="User avatar"
          className="object-contain shrink-0 self-stretch w-11 aspect-square"
        />
        <div className="flex flex-col self-stretch my-auto">
          <div className="text-sm font-bold text-neutral-700">Moni Roy</div>
          <div className="self-start text-xs font-semibold text-neutral-600">
            Admin
          </div>
        </div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0af2c405ea8e1fce85b9fb71ceda9930218fa336fc17b2259169c09511ba6f87?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
          alt="Dropdown icon"
          className="object-contain shrink-0 self-stretch my-auto aspect-square w-[18px]"
        />
      </div>
    </header>
  );
}

export default Header;
