/**
 * This code was generated by Builder.io.
 */
import React from "react";

function SalesDetails() {
  const yAxisLabels = ["100%", "80%", "60%", "40%", "20%"];
  const xAxisLabels = [
    "5k",
    "10k",
    "15k",
    "20k",
    "25k",
    "30k",
    "35k",
    "40k",
    "45k",
    "50k",
    "55k",
    "60k",
  ];

  return (
    <section className="flex flex-col px-8 pt-8 pb-14 mt-8 w-full bg-white rounded-2xl shadow-[6px_6px_54px_rgba(0,0,0,0.05)] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full leading-none max-md:max-w-full">
        <h2 className="my-auto text-2xl font-bold text-neutral-800">
          Sales Details
        </h2>
        <div className="flex gap-4 px-5 py-2.5 text-xs font-semibold text-right whitespace-nowrap bg-white rounded border border-solid border-neutral-300 text-zinc-800 text-opacity-40">
          <span>October</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/111fd0868388956f825ac25ee037644d295049379b5acf6e86ea84aed5304cc0?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
            alt="Dropdown icon"
            className="object-contain shrink-0 w-2.5 aspect-square"
          />
        </div>
      </div>
      <div className="flex flex-wrap gap-10 mt-12 text-xs font-semibold leading-none whitespace-nowrap text-zinc-800 text-opacity-40 max-md:mt-10">
        <div className="flex flex-col items-start self-start">
          {yAxisLabels.map((label, index) => (
            <div
              key={index}
              className={index > 0 ? "mt-12 max-md:mt-10" : "self-stretch"}
            >
              {label}
            </div>
          ))}
        </div>
        <div className="flex flex-col grow shrink-0 mt-1 text-center basis-0 w-fit max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a52f2d146cdbe1da0ed3456498dbefb5b00b25f7dcfbb5a58447674475f919d2?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
            alt="Sales graph"
            className="object-contain w-full bg-blend-normal aspect-[4.13] max-md:max-w-full"
          />
          <div className="flex flex-wrap gap-10 mt-6 max-w-full w-[961px]">
            {xAxisLabels.map((label, index) => (
              <div key={index} className={index === 0 ? "grow" : ""}>
                {label}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

export default SalesDetails;
