/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Sidebar() {
  const menuItems = [
    { label: "Dashboard", active: true },
    { label: "Products", active: false },
    { label: "Favorites", active: false },
    { label: "Inbox", active: false },
    { label: "Order Lists", active: false },
    { label: "Product Stock", active: false },
    { label: "Settings", active: false },
  ];

  return (
    <aside className="flex flex-col w-[17%] max-md:ml-0 max-md:w-full">
      <nav className="flex flex-col grow pt-6 pb-28 w-full text-sm font-semibold bg-white text-neutral-800 max-md:pb-24">
        {/* <div className="self-center text-2xl font-medium leading-none text-center text-black">
          3legant<span className="text-zinc-500">.</span>
        </div> */}
        {menuItems.map((item, index) => (
          <div
            key={index}
            className={`px-16 py-4 tracking-wide whitespace-nowrap ${
              item.active ? "relative text-white bg-black" : "bg-white bg-blend-normal"
            } max-md:px-5`}
          >
            {/* {item.active && (
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d7dd836e97996d3ae877a1ea2be9f0023017fbf8715f0d30379817a4b60aab92?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
                alt=""
                className="object-cover absolute inset-0 size-full"
              />
            )} */}
            {item.label}
          </div>
        ))}
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e56e7d294124136ca70785c836a45649f130014acf518fa0a888ecd5fc898e2?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
          alt="Decorative element"
          className="object-contain mt-4 w-full aspect-[250]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e56e7d294124136ca70785c836a45649f130014acf518fa0a888ecd5fc898e2?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
          alt="Decorative element"
          className="object-contain w-full aspect-[250] mt-[464px] max-md:mt-10"
        />
        <button className="self-center mt-4 tracking-wide">Logout</button>
      </nav>
    </aside>
  );
}

export default Sidebar;
