/**
 * This code was generated by Builder.io.
 */
import React from "react";

function StatCard({ title, value, trend, percentage }) {
  const trendColor = trend === "up" ? "text-teal-500" : "text-rose-500";
  const trendIcon =
    trend === "up"
      ? "https://cdn.builder.io/api/v1/image/assets/TEMP/0f7ef04ac61c42fab9deec33bba33c0e33bc4b7bfd461107f236cccdd2ea7cd8?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
      : "https://cdn.builder.io/api/v1/image/assets/TEMP/c204e582d8f28c977d22f130c06a7bd43f383052ca240f67720519d4a2dd6f3b?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7";
  const iconSrc =
    title === "Total Order"
      ? "https://cdn.builder.io/api/v1/image/assets/TEMP/7085bf66ea0c2e2c73a0de9d89bacc999f1c1e8e9250c6ac28db3984cadc58be?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
      : title === "Total Sales"
      ? "https://cdn.builder.io/api/v1/image/assets/TEMP/562aef7904becc25541ea565479ee379490be1373f0ff5416de2ed9cec46be16?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7"
      : "https://cdn.builder.io/api/v1/image/assets/TEMP/fb93adfa5d4dc5b7e493050d939ea4586f27ab266af501ed96f16a2bac4593f4?placeholderIfAbsent=true&apiKey=5936842654ff4c439a406c645fc0f7b7";

  return (
    <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col p-4 mx-auto w-full bg-white rounded-2xl shadow-[6px_6px_54px_rgba(0,0,0,0.05)] max-md:mt-8">
        <div className="flex gap-5 justify-between text-neutral-800">
          <div className="flex flex-col">
            <div className="text-base font-semibold bg-blend-normal max-md:mr-1.5">
              {title}
            </div>
            <div className="mt-4 text-3xl font-bold tracking-wider">
              {value}
            </div>
          </div>
          <img
            loading="lazy"
            src={iconSrc}
            alt=""
            className="object-contain shrink-0 self-start aspect-square w-[60px]"
          />
        </div>
        <div
          className={`flex gap-2 self-start mt-7 text-base font-semibold ${trendColor}`}
        >
          <img
            loading="lazy"
            src={trendIcon}
            alt={trend === "up" ? "Upward trend" : "Downward trend"}
            className="object-contain shrink-0 w-6 aspect-square"
          />
          <div className="basis-auto">
            <span className={trendColor}>{percentage}</span>{" "}
            <span className="text-zinc-600">
              {trend === "up" ? "Up from past week" : "Down from yesterday"}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default StatCard;
