/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CouponForm = () => {
  return (
    <div className="flex flex-col max-w-full w-[424px]">
      <div className="flex flex-col w-full max-md:max-w-full">
        <h2 className="text-xl font-medium leading-snug text-neutral-900 max-md:max-w-full">
          Have a coupon?
        </h2>
        <p className="mt-2 text-base leading-loose text-zinc-500 max-md:max-w-full">
          Add your code for an instant cart discount
        </p>
      </div>
      <form className="flex flex-col justify-center px-4 mt-4 w-full text-base font-medium tracking-tight leading-7 border border-solid border-zinc-500 max-w-[424px] min-h-[52px] max-md:max-w-full">
        <div className="flex gap-2 items-center w-full border-b border-solid border-b-zinc-500 border-b-opacity-50 min-h-[52px]">
          <label htmlFor="couponInput" className="sr-only">
            Enter coupon code
          </label>
          <div className="flex flex-1 shrink gap-2 items-center self-stretch my-auto basis-0 min-w-[240px] text-zinc-500">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac6e35b11c3868c633b70bd515e27896161dadb8ed2f15747d420eb9082e2f55?placeholderIfAbsent=true&apiKey=553755d898d94809aa76715ffb4c295b"
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              alt=""
            />
            <input
              type="text"
              id="couponInput"
              className="flex-1 shrink self-stretch my-auto basis-0 bg-transparent border-none outline-none"
              placeholder="Coupon Code"
            />
          </div>
          <button
            type="submit"
            className="flex gap-0.5 items-center self-stretch my-auto whitespace-nowrap border-0 border-solid border-neutral-900 text-neutral-900"
          >
            Apply
          </button>
        </div>
      </form>
    </div>
  );
};

export default CouponForm;
