/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <h1>
      3legant<span className="text-zinc-500">.</span>
    </h1>
  );
}

export default Logo;
