/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Link } from "react-router-dom";

const Breadcrumb = () => {
  return (
    <nav
      aria-label="Breadcrumb"
      className="flex gap-4 items-start self-start pl-40 text-sm font-medium leading-6 text-zinc-600 max-md:pl-5 max-md:max-w-full"
    >
      <Link to="/" className="flex gap-1 items-center whitespace-nowrap">
        <div className="self-stretch my-auto">Home</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a4523bb5140e74b46ba08a902f8285eda39d3a7691ab1b365eeacde94c5018e0?placeholderIfAbsent=true&apiKey=553755d898d94809aa76715ffb4c295b"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
        />
      </Link>
      <Link to="/shop" className="flex gap-1 items-center whitespace-nowrap">
        <div className="self-stretch my-auto">Shop</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a4523bb5140e74b46ba08a902f8285eda39d3a7691ab1b365eeacde94c5018e0?placeholderIfAbsent=true&apiKey=553755d898d94809aa76715ffb4c295b"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
        />
      </Link>
      <Link to="/shop/living-room" className="flex gap-1 items-center">
        <div className="self-stretch my-auto">Living Room</div>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a4523bb5140e74b46ba08a902f8285eda39d3a7691ab1b365eeacde94c5018e0?placeholderIfAbsent=true&apiKey=553755d898d94809aa76715ffb4c295b"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-3 aspect-square"
        />
      </Link>
      <span className="gap-1 self-stretch whitespace-nowrap text-neutral-900">
        Product
      </span>
    </nav>
  );
};

export default Breadcrumb;
